export const videos = [
  {
    id: "v1",
    title: "Build YouTube Clone using HTML CSS and JavaScript",
    thumbnail: "./assets/thumbnail1.jpg",
    channelName: "Code Studio",
    channelAvatar: "https://i.pravatar.cc/40?img=12",
    views: "1.2M views",
    uploaded: "2 weeks ago",
    duration: "12:45",
    category: "Web-development"
  },
  {
    id: "v2",
    title: "React Project Ideas for Portfolio 2025",
    thumbnail: "./assets/thumbnail2.jpg",
    channelName: "Dev World",
    channelAvatar: "https://i.pravatar.cc/40?img=5",
    views: "845K views",
    uploaded: "1 month ago",
    duration: "18:20",
    category: "React"
  },
  {
    id: "v3",
    title: "JavaScript ES6 Crash Course",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "JS Mastery",
    channelAvatar: "https://i.pravatar.cc/40?img=8",
    views: "640K views",
    uploaded: "3 weeks ago",
    duration: "09:10",
    category: "Javascript"
  },
  {
    id: "v4",
    title: "CSS Grid Complete Guide",
    thumbnail: "./assets/thumbnail4.jpg",
    channelName: "Frontend Lab",
    channelAvatar: "./assets/thumbnail5.jpg",
    views: "420K views",
    uploaded: "5 days ago",
    duration: "07:32",
    category: "CSS"
  },
  {
    id: "v5",
    title: "AI Tools Every Developer Should Know",
    thumbnail: "./assets/thumbnail6.jpg",
    channelName: "AI Simplified",
    channelAvatar: "https://i.pravatar.cc/40?img=20",
    views: "980K views",
    uploaded: "1 week ago",
    duration: "10:55",
    category: "AI"
  },
  {
    id: "v6",
    title: "GitHub Beginner Tutorial — Full Guide",
    thumbnail: "./assets/thumbnail8.jpg",
    channelName: "Code Basics",
    channelAvatar: "https://i.pravatar.cc/40?img=18",
    views: "1.8M views",
    uploaded: "2 months ago",
    duration: "22:14",
    category: "Github"
  },
  {
    id: "v7",
    title: "Build Real Projects to Get Developer Job",
    thumbnail: "./assets/thumbnail9.jpg",
    channelName: "Career Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=22",
    views: "310K views",
    uploaded: "6 days ago",
    duration: "14:02",
    category: "Projects"
  },
  {
    id: "v8",
    title: "Coding Music Mix for Focus",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "Music Hub",
    channelAvatar: "https://i.pravatar.cc/40?img=30",
    views: "5M views",
    uploaded: "3 months ago",
    duration: "1:12:10",
    category: "Music"
  },
  {
    id: "v9",
    title: "Tech News Weekly — AI Updates",
    thumbnail: "./assets/thumbnail1.jpg",
    channelName: "Tech News",
    channelAvatar: "https://i.pravatar.cc/40?img=25",
    views: "210K views",
    uploaded: "2 days ago",
    duration: "11:08",
    category: "News"
  },
  {
    id: "v10",
    title: "Live Coding — Build Navbar from Scratch",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "Live Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=27",
    views: "95K views",
    uploaded: "1 day ago",
    duration: "36:50",
    category: "Live"
  },
  {
    id: "v11",
    title: "Advanced CSS Animations Tutorial",
    thumbnail: "./assets/thumbnail4.jpg",
    channelName: "Frontend Pro",
    channelAvatar: "https://i.pravatar.cc/40?img=31",
    views: "380K views",
    uploaded: "4 days ago",
    duration: "15:12",
    category: "CSS"
  },
  {
    id: "v12",
    title: "React Folder Structure Explained",
    thumbnail: "./assets/thumbnail8.jpg",
    channelName: "React Guide",
    channelAvatar: "https://i.pravatar.cc/40?img=32",
    views: "520K views",
    uploaded: "2 weeks ago",
    duration: "13:48",
    category: "React"
  },
  {
    id: "v13",
    title: "JavaScript Async Await Masterclass",
    thumbnail: "./assets/thumbnail2.jpg",
    channelName: "JS Academy",
    channelAvatar: "https://i.pravatar.cc/40?img=33",
    views: "760K views",
    uploaded: "1 month ago",
    duration: "21:05",
    category: "Javascript"
  },
  {
    id: "v14",
    title: "Build AI Chat UI with Vanilla JS",
    thumbnail: "./assets/thumbnail4.jpg",
    channelName: "AI Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=34",
    views: "290K views",
    uploaded: "3 days ago",
    duration: "17:40",
    category: "AI"
  },
  {
    id: "v15",
    title: "GitHub Workflow for Teams",
    thumbnail: "./assets/thumbnail5.jpg",
    channelName: "Dev Collaboration",
    channelAvatar: "https://i.pravatar.cc/40?img=35",
    views: "190K views",
    uploaded: "2 weeks ago",
    duration: "11:55",
    category: "Github"
  },
  {
    id: "v16",
    title: "Build Responsive Dashboard UI",
    thumbnail: "./assets/thumbnail6.jpg",
    channelName: "UI Master",
    channelAvatar: "https://i.pravatar.cc/40?img=36",
    views: "610K views",
    uploaded: "1 month ago",
    duration: "19:10",
    category: "Projects"
  },
  {
    id: "v17",
    title: "Coding Podcast — Developer Mindset",
    thumbnail: "./assets/thumbnail7.jpg",
    channelName: "Dev Talks",
    channelAvatar: "https://i.pravatar.cc/40?img=37",
    views: "140K views",
    uploaded: "5 days ago",
    duration: "42:18",
    category: "Podcasts"
  },
  {
    id: "v18",
    title: "LoFi Coding Music Mix",
    thumbnail: "./assets/thumbnail8.jpg",
    channelName: "Focus Music",
    channelAvatar: "https://i.pravatar.cc/40?img=38",
    views: "2.1M views",
    uploaded: "2 months ago",
    duration: "1:05:12",
    category: "Music"
  },
  {
    id: "v19",
    title: "Weekly Tech News Roundup",
    thumbnail: "./assets/thumbnail9.jpg",
    channelName: "Tech Today",
    channelAvatar: "https://i.pravatar.cc/40?img=39",
    views: "220K views",
    uploaded: "6 days ago",
    duration: "12:20",
    category: "News"
  },
  {
    id: "v20",
    title: "Live Build — CSS Landing Page",
    thumbnail: "./assets/thumbnail2.jpg",
    channelName: "Live Coding",
    channelAvatar: "https://i.pravatar.cc/40?img=40",
    views: "88K views",
    uploaded: "1 day ago",
    duration: "38:05",
    category: "Live"
  },
  {
    id: "v21",
    title: "Web Development Roadmap 2025",
    thumbnail: "./assets/thumbnail6.jpg",
    channelName: "Career Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=41",
    views: "1.1M views",
    uploaded: "3 weeks ago",
    duration: "16:40",
    category: "Web-development"
  },
  {
    id: "v22",
    title: "React Performance Optimization",
    thumbnail: "./assets/thumbnail2.jpg",
    channelName: "React Pro",
    channelAvatar: "https://i.pravatar.cc/40?img=42",
    views: "300K views",
    uploaded: "2 weeks ago",
    duration: "14:22",
    category: "React"
  },
  {
    id: "v23",
    title: "JavaScript Interview Questions",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "Interview Prep",
    channelAvatar: "https://i.pravatar.cc/40?img=43",
    views: "670K views",
    uploaded: "1 month ago",
    duration: "25:10",
    category: "Javascript"
  },
  {
    id: "v24",
    title: "CSS Tricks You Didn’t Know",
    thumbnail: "./assets/thumbnail9.jpg",
    channelName: "CSS Wizard",
    channelAvatar: "https://i.pravatar.cc/40?img=44",
    views: "410K views",
    uploaded: "9 days ago",
    duration: "10:30",
    category: "CSS"
  },
  {
    id: "v25",
    title: "Build AI Dashboard UI",
    thumbnail: "./assets/thumbnail5.jpg",
    channelName: "AI UI Lab",
    channelAvatar: "https://i.pravatar.cc/40?img=45",
    views: "205K views",
    uploaded: "4 days ago",
    duration: "18:55",
    category: "AI"
  },
  {
    id: "v26",
    title: "GitHub Advanced Tips",
    thumbnail: "./assets/thumbnail6.jpg",
    channelName: "GitHub Insider",
    channelAvatar: "https://i.pravatar.cc/40?img=46",
    views: "150K views",
    uploaded: "2 weeks ago",
    duration: "09:42",
    category: "Github"
  },
  {
    id: "v27",
    title: "Build SaaS UI Project",
    thumbnail: "./assets/thumbnail7.jpg",
    channelName: "Startup Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=47",
    views: "280K views",
    uploaded: "8 days ago",
    duration: "20:11",
    category: "Projects"
  },
  {
    id: "v28",
    title: "Developer Podcast — Productivity",
    thumbnail: "./assets/thumbnail9.jpg",
    channelName: "Dev Talks",
    channelAvatar: "https://i.pravatar.cc/40?img=48",
    views: "95K views",
    uploaded: "3 days ago",
    duration: "39:02",
    category: "Podcasts"
  },
  {
    id: "v29",
    title: "Focus Coding Mix — Deep Work",
    thumbnail: "./assets/thumbnail7.jpg",
    channelName: "Focus Beats",
    channelAvatar: "https://i.pravatar.cc/40?img=49",
    views: "3M views",
    uploaded: "2 months ago",
    duration: "1:18:00",
    category: "Music"
  },
  {
    id: "v30",
    title: "Live Build — JavaScript App",
    thumbnail: "./assets/thumbnail6.jpg",
    channelName: "Live Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=50",
    views: "120K views",
    uploaded: "2 days ago",
    duration: "41:33",
    category: "Live"
  },
  {
    id: "v1",
    title: "Build YouTube Clone using HTML CSS and JavaScript",
    thumbnail: "./assets/thumbnail1.jpg",
    channelName: "Code Studio",
    channelAvatar: "https://i.pravatar.cc/40?img=12",
    views: "1.2M views",
    uploaded: "2 weeks ago",
    duration: "12:45",
    category: "Web-development"
  },
  {
    id: "v2",
    title: "React Project Ideas for Portfolio 2025",
    thumbnail: "./assets/thumbnail2.jpg",
    channelName: "Dev World",
    channelAvatar: "https://i.pravatar.cc/40?img=5",
    views: "845K views",
    uploaded: "1 month ago",
    duration: "18:20",
    category: "React"
  },
  {
    id: "v3",
    title: "JavaScript ES6 Crash Course",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "JS Mastery",
    channelAvatar: "https://i.pravatar.cc/40?img=8",
    views: "640K views",
    uploaded: "3 weeks ago",
    duration: "09:10",
    category: "Javascript"
  },
  {
    id: "v4",
    title: "CSS Grid Complete Guide",
    thumbnail: "./assets/thumbnail4.jpg",
    channelName: "Frontend Lab",
    channelAvatar: "./assets/thumbnail5.jpg",
    views: "420K views",
    uploaded: "5 days ago",
    duration: "07:32",
    category: "CSS"
  },
  {
    id: "v5",
    title: "AI Tools Every Developer Should Know",
    thumbnail: "./assets/thumbnail6.jpg",
    channelName: "AI Simplified",
    channelAvatar: "https://i.pravatar.cc/40?img=20",
    views: "980K views",
    uploaded: "1 week ago",
    duration: "10:55",
    category: "AI"
  },
  {
    id: "v6",
    title: "GitHub Beginner Tutorial — Full Guide",
    thumbnail: "./assets/thumbnail8.jpg",
    channelName: "Code Basics",
    channelAvatar: "https://i.pravatar.cc/40?img=18",
    views: "1.8M views",
    uploaded: "2 months ago",
    duration: "22:14",
    category: "Github"
  },
  {
    id: "v7",
    title: "Build Real Projects to Get Developer Job",
    thumbnail: "./assets/thumbnail9.jpg",
    channelName: "Career Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=22",
    views: "310K views",
    uploaded: "6 days ago",
    duration: "14:02",
    category: "Projects"
  },
  {
    id: "v8",
    title: "Coding Music Mix for Focus",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "Music Hub",
    channelAvatar: "https://i.pravatar.cc/40?img=30",
    views: "5M views",
    uploaded: "3 months ago",
    duration: "1:12:10",
    category: "Music"
  },
  {
    id: "v9",
    title: "Tech News Weekly — AI Updates",
    thumbnail: "./assets/thumbnail1.jpg",
    channelName: "Tech News",
    channelAvatar: "https://i.pravatar.cc/40?img=25",
    views: "210K views",
    uploaded: "2 days ago",
    duration: "11:08",
    category: "News"
  },
  {
    id: "v10",
    title: "Live Coding — Build Navbar from Scratch",
    thumbnail: "./assets/thumbnail3.jpg",
    channelName: "Live Dev",
    channelAvatar: "https://i.pravatar.cc/40?img=27",
    views: "95K views",
    uploaded: "1 day ago",
    duration: "36:50",
    category: "Live"
  },
];
